"""Fetch backend calibration snapshots from IBM Quantum and record provenance for reproducible runs."""

import json
import os
import shlex
import subprocess
from datetime import datetime, timezone
try:
    from importlib import metadata as importlib_metadata
except ImportError:
    import importlib_metadata


def _env_flag(name: str, default: bool = False) -> bool:
    raw = os.getenv(name)
    if raw is None:
        return bool(default)
    return str(raw).strip().lower() in {"1", "true", "yes", "y", "on"}


def _package_version(name: str):
    try:
        return importlib_metadata.version(name)
    except Exception:
        return None


def _git_revision(project_root: str):
    try:
        return subprocess.check_output(
            ["git", "rev-parse", "HEAD"],
            cwd=project_root,
            stderr=subprocess.DEVNULL,
            text=True,
        ).strip()
    except Exception:
        return None


def _serialize_runtime_object(obj):
    if obj is None:
        return None
    if hasattr(obj, "to_dict"):
        try:
            return obj.to_dict()
        except Exception:
            pass
    if hasattr(obj, "__dict__"):
        try:
            return dict(obj.__dict__)
        except Exception:
            pass
    return {"repr": repr(obj)}


def _backend_name(backend):
    name = getattr(backend, "name", None)
    if callable(name):
        try:
            name = name()
        except Exception:
            name = None
    return str(name) if name else None


def _backend_num_qubits(backend):
    value = getattr(backend, "num_qubits", None)
    if value is not None:
        try:
            return int(value)
        except Exception:
            pass
    try:
        config = backend.configuration()
        value = getattr(config, "num_qubits", None)
        if value is None and isinstance(config, dict):
            value = config.get("num_qubits")
        return int(value) if value is not None else None
    except Exception:
        return None


def _backend_is_simulator(backend):
    value = getattr(backend, "simulator", None)
    if value is not None:
        return bool(value)
    try:
        config = backend.configuration()
        value = getattr(config, "simulator", None)
        if value is None and isinstance(config, dict):
            value = config.get("simulator")
        return bool(value)
    except Exception:
        return False


def discover_backend_names(service):
    min_qubits = int(os.getenv("DOWNLOAD_MIN_QUBITS", "1"))
    max_backends = int(os.getenv("DOWNLOAD_MAX_BACKENDS", "0"))
    include_simulators = _env_flag("DOWNLOAD_INCLUDE_SIMULATORS", default=False)
    name_filter = os.getenv("DOWNLOAD_BACKEND_NAME_FILTER", "").strip().lower()

    try:
        backends = service.backends()
    except TypeError:
        backends = service.backends
    except Exception as e:
        raise RuntimeError(f"Could not list available IBM Quantum backends: {e}") from e

    rows = []
    for backend in backends:
        name = _backend_name(backend)
        if not name:
            continue
        num_qubits = _backend_num_qubits(backend) or 0
        if num_qubits < min_qubits:
            continue
        if not include_simulators and _backend_is_simulator(backend):
            continue
        if name_filter and name_filter not in name.lower():
            continue
        rows.append((name, int(num_qubits)))

    rows = sorted(set(rows), key=lambda item: (-item[1], item[0]))
    if max_backends > 0:
        rows = rows[:max_backends]
    return [name for name, _num_qubits in rows], rows


def write_active_calibration_env(downloaded, output_dir, primary_backend_name=None):
    usable = [
        row for row in downloaded
        if row.get("output_path") and os.path.exists(row["output_path"])
    ]
    if not usable:
        return None

    primary = None
    if primary_backend_name:
        for row in usable:
            if row.get("backend_name") == primary_backend_name:
                primary = row
                break
    if primary is None:
        primary = usable[0]

    paths = [os.path.abspath(row["output_path"]) for row in usable]
    primary_path = os.path.abspath(primary["output_path"])
    joined = ",".join(paths)

    active_env_path = os.path.join(output_dir, "active_calibration_files.env")
    with open(active_env_path, "w") as f:
        f.write("# Auto-generated by download_calibrations.py\n")
        f.write(f"export QUANTUM_CALIBRATION_FILE={shlex.quote(primary_path)}\n")
        f.write(f"export REVIEW_CALIBRATION_FILES={shlex.quote(joined)}\n")
        f.write(f"export PROXY_MATRIX_CALIBRATION_FILES={shlex.quote(joined)}\n")
        f.write(f"export DOWNLOADED_CALIBRATION_FILES={shlex.quote(joined)}\n")
    return active_env_path, primary_path, joined


def download_backend_calibration(service, backend_name: str, output_dir: str, snapshot_iso: str | None = None):
    backend = service.backend(backend_name)
    requested_datetime = None
    if snapshot_iso:
        requested_datetime = datetime.fromisoformat(snapshot_iso.replace("Z", "+00:00"))

    try:
        props = backend.properties(refresh=True, datetime=requested_datetime)
    except Exception:
        if requested_datetime is not None:
            props = backend.properties(refresh=True)
        else:
            raise

    if props is None:
        raise RuntimeError(f"No backend properties are available for {backend_name}.")

    config = None
    status = None
    try:
        config = backend.configuration()
    except Exception:
        config = None
    try:
        status = backend.status()
    except Exception:
        status = None

    payload = _serialize_runtime_object(props)
    if not isinstance(payload, dict):
        raise RuntimeError(f"Could not serialize backend properties for {backend_name}.")

    payload["backend_name"] = payload.get("backend_name", getattr(backend, "name", backend_name))
    payload["backend_version"] = payload.get("backend_version", getattr(backend, "backend_version", None))
    payload["processor_type"] = getattr(backend, "processor_type", None)
    payload["num_qubits"] = getattr(backend, "num_qubits", None)
    payload["downloaded_at_utc"] = datetime.now(timezone.utc).isoformat()
    payload["requested_datetime"] = snapshot_iso
    payload["source"] = {
        "service": "qiskit_ibm_runtime.QiskitRuntimeService",
        "backend_name": backend_name,
        "configuration": _serialize_runtime_object(config),
        "status": _serialize_runtime_object(status),
    }

    os.makedirs(output_dir, exist_ok=True)
    if snapshot_iso:
        stamp = (
            snapshot_iso.replace(":", "")
            .replace("-", "")
            .replace("+", "p")
            .replace("Z", "z")
        )
        output_path = os.path.join(output_dir, f"{backend_name}_{stamp}_calibration.json")
    else:
        output_path = os.path.join(output_dir, f"{backend_name}_calibration.json")
    with open(output_path, "w") as f:
        json.dump(payload, f, indent=2, default=str)
    return output_path, payload


if __name__ == "__main__":
    project_root = os.path.dirname(os.path.abspath(__file__))
    output_dir = os.path.abspath(os.getenv("DOWNLOAD_CALIBRATION_DIR", os.path.join(project_root, "downloaded_calibrations")))
    requested_backend_names = os.getenv("DOWNLOAD_BACKEND_NAMES", "auto").strip()
    backend_names = [part.strip() for part in requested_backend_names.split(",") if part.strip()]
    snapshot_iso = os.getenv("DOWNLOAD_SNAPSHOT_ISO", "").strip() or None
    snapshot_isos = [
        part.strip()
        for part in os.getenv("DOWNLOAD_SNAPSHOT_ISOS", "").split(",")
        if part.strip()
    ]
    if snapshot_iso and not snapshot_isos:
        snapshot_isos = [snapshot_iso]
    if not snapshot_isos:
        snapshot_isos = [None]
    fail_fast = _env_flag("DOWNLOAD_FAIL_FAST", default=False)

    try:
        from qiskit_ibm_runtime import QiskitRuntimeService
    except Exception as e:
        raise RuntimeError(
            "qiskit-ibm-runtime is required to download fresh calibration files. "
            "Install it and ensure your IBM Quantum account is configured."
        ) from e

    token = (
        os.getenv("IBM_QUANTUM_API_TOKEN", "").strip()
        or os.getenv("QISKIT_IBM_TOKEN", "").strip()
        or None
    )
    instance = (
        os.getenv("IBM_QUANTUM_CRN", "").strip()
        or os.getenv("IBM_QUANTUM_INSTANCE", "").strip()
        or None
    )
    channel = os.getenv("IBM_QUANTUM_CHANNEL", "").strip() or ("ibm_cloud" if instance else None)
    if token:
        kwargs = {"token": token}
        if channel:
            kwargs["channel"] = channel
        if instance:
            kwargs["instance"] = instance
        service = QiskitRuntimeService(**kwargs)
    else:
        service = QiskitRuntimeService()
    downloaded = []
    failed = []

    if not backend_names or any(item.lower() in {"auto", "available", "discover"} for item in backend_names):
        backend_names, discovered_rows = discover_backend_names(service)
        if not backend_names:
            raise RuntimeError("No accessible IBM Quantum backends were discovered for this account/instance.")
        print("Discovered accessible IBM Quantum backends:")
        for name, num_qubits in discovered_rows:
            print(f"  {name} ({num_qubits} qubits)")

    print("Downloading calibration snapshots...")
    print(f"Backends:   {', '.join(backend_names)}")
    print(f"Output dir: {output_dir}")
    print("Snapshots:  " + ", ".join([item if item else "latest" for item in snapshot_isos]))

    for requested_snapshot_iso in snapshot_isos:
        for backend_name in backend_names:
            try:
                output_path, payload = download_backend_calibration(
                    service=service,
                    backend_name=backend_name,
                    output_dir=output_dir,
                    snapshot_iso=requested_snapshot_iso,
                )
                downloaded.append(
                    {
                        "backend_name": backend_name,
                        "requested_datetime": requested_snapshot_iso,
                        "output_path": output_path,
                        "backend_version": payload.get("backend_version"),
                        "last_update_date": payload.get("last_update_date"),
                        "num_qubits": payload.get("num_qubits"),
                        "processor_type": payload.get("processor_type"),
                    }
                )
                print(f"  OK  {backend_name} [{requested_snapshot_iso or 'latest'}] -> {output_path}")
            except Exception as e:
                failed.append({"backend_name": backend_name, "requested_datetime": requested_snapshot_iso, "error": str(e)})
                print(f"  FAIL {backend_name} [{requested_snapshot_iso or 'latest'}]: {e}")
                if fail_fast:
                    raise

    manifest = {
        "downloaded_at_utc": datetime.now(timezone.utc).isoformat(),
        "requested_backends": backend_names,
        "requested_backend_names_raw": requested_backend_names,
        "snapshot_iso": snapshot_iso,
        "snapshot_isos": snapshot_isos,
        "downloaded": downloaded,
        "failed": failed,
        "metadata": {
            "git_revision": _git_revision(project_root),
            "python_version": os.sys.version,
            "package_versions": {
                "qiskit": _package_version("qiskit"),
                "qiskit-ibm-runtime": _package_version("qiskit-ibm-runtime"),
            },
        },
    }
    os.makedirs(output_dir, exist_ok=True)
    manifest_path = os.path.join(output_dir, "calibration_manifest.json")
    with open(manifest_path, "w") as f:
        json.dump(manifest, f, indent=2, default=str)

    print(f"Saved manifest to {manifest_path}")
    if not downloaded:
        raise RuntimeError("Calibration download did not produce any usable files.")
    active = write_active_calibration_env(
        downloaded,
        output_dir,
        primary_backend_name=os.getenv("PRIMARY_BACKEND_NAME", "").strip() or None,
    )
    if active:
        active_env_path, primary_path, joined = active
        print(f"Saved active calibration env to {active_env_path}")
        print(f"Primary calibration: {primary_path}")
        print(f"Active calibration files: {joined}")
